History
silicon-heaven/shv-doc pull request #33
Opened 2024-03-19 10:31 UTC by Cynerd

2024-03-20 13:58 UTC, syyyr commented on src/rpcmethods/history.md
> +`.history/test/device/foo/status` must be valid and discoverable.
This means that in HistoryProvider, whenever I fetch log files, I'll have to parse all the paths of all events in the log file to make this tree.

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +  this field is not specified.
Does this worth to implement?

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +  if `"anchor"` field was `true`.
+ flag whether record is spontaneous or keep one

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +* *Int* with signal's access level. The default if not specified is *Read*.
Why do we need to log access level?

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +  information in a single log file.
I suggest to introduce `snapshot` or `anchor` name for this part of log.

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +The rest of the file must contain *List*s with following columns:
Column names (to be referenced in documentation) would be fine.

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +* *Bool* if this is repeated record. File log must start with repeat of all
also `keep` records must be tagged

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +Trigger the synchronization manually right now.
How the synchronization process looks like.

2024-03-20 14:43 UTC, fvacek commented on src/rpcmethods/history.md
> +Logs are recorded with device's time and that include timezone set on the
Why UTC is not used?

2024-03-21 08:34 UTC, Cynerd commented on src/rpcmethods/history.md
> +`.history/test/device/foo/status` must be valid and discoverable.
You can do that on demand also.

To implement `getLog`, you must have an index with the correct time (with time modifications applied) base so you can also keep index of paths to the appropriate logs (that is records and log files not exactly specific log line).

By having this tree you do not have to query multiple logs and instead it is history's responsibility to look for it based on the used path.

2024-03-21 08:34 UTC, Cynerd commented on src/rpcmethods/history.md
> +`.history/test/device/foo/status` must be valid and discoverable.
Allows aggregated access. See my next answer about aggregation.

2024-03-21 08:37 UTC, Cynerd commented on src/rpcmethods/history.md
> +provided only if aggregated log access is provided and in such case it is
Aggregated or, in other words, combined access all logs that history has (and provides in this way).

It is not some technical term that needs definition. It is used here in its English word meaning.

2024-03-21 08:40 UTC, Cynerd commented on src/rpcmethods/history.md
> +  this field is not specified.
It serves usage such as "When was the last maintenance" or "Tell me three last maintenance actions". Or an efficient way to ask, "is there any maintenance in the last year?".

2024-03-21 09:30 UTC, Cynerd commented on src/rpcmethods/history.md
> +  if `"anchor"` field was `true`.
That is what anchor is. `getLog` otherwise doesn't provide keep and repeated records. Those have meaning when fetching and/or indexing logs (to construct the anchor records) but not otherwise.

2024-03-21 09:32 UTC, Cynerd commented on src/rpcmethods/history.md
> +* *Int* with signal's access level. The default if not specified is *Read*.
To filter logs in `getLog` based on the access level of the caller.

2024-03-21 09:36 UTC, Cynerd commented on src/rpcmethods/history.md
> +  information in a single log file.
I intentionally try to create a difference between them by naming it differently but using "anchor" might  be acceptable because it at least looks somewhat the same way as anchor in `getLog`.

2024-03-21 09:51 UTC, Cynerd commented on src/rpcmethods/history.md
> +* *Bool* if this is repeated record. File log must start with repeat of all
There are no keep records in file logs. That is why I am trying to use different naming schema to make that clear. Those are two different concepts.

"keep records" are dispersed in the logs timeline while "repeated" (or we can say "anchor") records are all at one location.

There is no need to explicitly compare them because they are named differently, described differently and thus different. You only seem to mix them up because you are interpreting them as just a "snapshot" alias.

2024-03-21 09:51 UTC, Cynerd commented on src/rpcmethods/history.md
> +Trigger the synchronization manually right now.
That is up to the implementation. It must use methods available to it but the exact implementation is not defined. That is my intention to not hardcode us to the corner.

2024-03-21 09:51 UTC, Cynerd commented on src/rpcmethods/history.md
> +Logs are recorded with device's time and that include timezone set on the
Because that is ISO 8601 format. Using UTC time with time zone is sometimes better (because you can use stupid string sort even after timezone change), but by using ISO format while specifying UTC time instead creates huge confusion.

The alternative would be not to use ISO 8601 and instead use format that can't be confused with it.

2024-03-21 11:05 UTC, Cynerd commented on src/rpcmethods/history.md
> +The rest of the file must contain *List*s with following columns:
Added but I am not sure if it improves the documentation or not.

2024-04-25 10:06 UTC, fvacek commented on src/rpcmethods/history.md
> +`.history/test/device/foo/status` must be valid and discoverable.
Well according to our discussion, this virtual tree is optional now.

2024-04-25 10:51 UTC, fvacek requested changes

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +| `getLog` | `.history/**` | `ret(param)` | HintLargeResult | Browse |
Read access

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +exception of `.app`, `.records` and `.files`. In other words this must be
When we can have `.history/.app`?

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +  request retrieval if not provided.
If there are more records with same timestamp `TS` in the log and this timestamp is last one in `getLog` result, then all the records with `TS` must be returned. In other case, follow up `getLog` with `since == TS` might skip records.

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +  that this date and time can precede `"since"` and in such case logs returned
I'm still not convinced, if `until < since` is worth to have. The use-case is to have possibility to find most recent occurrence of some record. It seems to me like if want to use `getLog` for `revFind`, moreover the `snapshot` parameter has not good meaning in this particular case.

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +* `6`(*Value*): with signal's value (parameter). The default if not specified is
`value`

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +  used only if `"anchor"` field was `true`.
Does `anchor` mean injected by logger? Like `keep`?

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +records but it doesn't have to be monotonic (there can be unused IDs).
but it doesn't have to be continuous

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +  * `4`(*timeAbiq*) time ambiguity record. This is information that date and
`timeAmbiq`

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +expected to have *Map* while rest should be *List*s.
Why not Map?

2024-04-25 10:51 UTC, fvacek commented on src/rpcmethods/history.md
> +Logs are recorded with device's time and that include timezone set on the
We can use UTC only (without TZ) and store TZ in the log header.

2024-04-25 10:53 UTC, Cynerd commented on src/rpcmethods/history.md
> +| `getLog` | `.history/**` | `ret(param)` | HintLargeResult | Browse |
See paragraph on line 131:
```
The method itself has only Browse access level but it must filter provided logs
based on their access level and thus user with low access level might not see
all that is provided.
```

It can't have read access because it would by design removed access to signals with lower access lever than read.

2024-04-25 10:55 UTC, fvacek commented on src/rpcmethods/history.md
> +  if `"anchor"` field was `true`.
Unfortunetelly also `getLog` can contain non-spontaneous records in different places than snapshot. For example, PLC sends all Vetras state after boot, even if tram has passed long time ago.

2024-04-25 10:55 UTC, Cynerd commented on src/rpcmethods/history.md
> +exception of `.app`, `.records` and `.files`. In other words this must be
When `.history` is a separate application that runs independently of broker. There can be only one such application but this way we can have history split from broker (or it can be the same app).

2024-05-02 21:39 UTC, fvacek approved these changes

2024-05-02 21:40 UTC, merged