Add userId definition and login nonce retransmition rules.
silicon-heaven/shv-doc pull request #43
Opened 2024-08-02 15:23 UTC by fvacek

2024-08-19 09:04 UTC, Cynerd requested changes
Now when we use broker's name we probably should add `.broker:name` getter to `identify` brokers in the tree because it is a bit different over `.app:name`. That was suppose to be name of the application while the broker name is an identifier (imagine that you have shbroker application that runs on different locations and thus have different name but `.app:name` should still tell you that it is the shvbroker).

2024-08-19 09:04 UTC, Cynerd commented on src/rpcmessage.md
> +broker names along the RPC message path through brokers' hierarchy. The format
```suggestion
broker names along the RPC message path through the brokers hierarchy. The format
```
I am not sure if it should be ownership of hierarchy for the broker here. It doesn't make sense to me. It is rather just Broker hierarchy.

2024-08-19 10:47 UTC, Cynerd commented on src/rpcmessage.md
> +is`user-name1:broker-name1;user-name2:broker-name2;...`, for example:
Thinking about this. Wouldn't it be more consistent to have it `user-name1/broker-name1/user-name2:broker-name2`? It would be more clear that it is some level difference over `;`. Just a suggestion to think about.

2024-08-26 10:24 UTC, fvacek commented on src/rpcmessage.md
> +is`user-name1:broker-name1;user-name2:broker-name2;...`, for example:
Do you mean `user-name1:broker-name1/user-name2:broker-name2`?, I personally do not suggest slashes, they are used paths obviously and they can be confusing in user-id. Maybe we can  find some other delimiter than '/' which can mimic some hierarchy.

2024-08-26 12:18 UTC, fvacek commented
> Now when we use broker's name we probably should add `.broker:name` getter to `identify` brokers in the tree because it is a bit different over `.app:name`. That was suppose to be name of the application while the broker name is an identifier (imagine that you have shbroker application that runs on different locations and thus have different name but `.app:name` should still tell you that it is the shvbroker).

What about `broker:id`?

2024-09-25 20:33 UTC, merged