rpctypes: Add type hints definition
silicon-heaven/shv-doc pull request #51
Opened 2024-12-17 07:41 UTC by Cynerd

The type hints definition should be used to hint on the expected parameter and result of the methods. It is designed to be parsed by decision tree.

This commit also defines parameter and result type for all common RPC methods definitions. It is included in the single table as a reference for the 'dir' description of that method. The signals are also described this way and thus their description united across the documentation.

The 'dir' method's result now directly references type descriptions as the format to be used.

2025-01-02 17:02 UTC, fvacek commented on src/rpctypes.md
> +decimal          = "d", ["(", [decimal number], ",", [decimal number], [",", decimal number], ")"] unit;
```suggestion
decimal          = "d", ["(", [decimal number], ",", [decimal number], [",", decimal number], ")"], unit;
```

2025-01-02 17:02 UTC, fvacek commented on src/rpctypes.md
> +integer          = "i", ["(", [number], ",", [number], ")"], unit;
```suggestion
integer          = "i", ["(", [number], ",", [number], ")"], [unit];
```
shouldn't be unit also optional?

2025-01-02 18:47 UTC, Cynerd commented on src/rpctypes.md
> +integer          = "i", ["(", [number], ",", [number], ")"], unit;
Unit is actually an optional text and thus it can be no text and thus still present.

2025-01-02 18:50 UTC, Cynerd commented on src/rpctypes.md
> +i{TYPE}
What that would mean? Possibly the alias for `i{?}`, but that is just one character less while introducing the encoding ambiguity... I think that it is not worth it.

2025-01-02 18:50 UTC, Cynerd commented on src/rpctypes.md
> +* `[i:id,s:name,lastLogin:t|n]` First item must be integer, second item string
```suggestion
* `[i:id,s:name,t|n:lastLogin]` First item must be integer, second item string
```

2025-01-02 18:50 UTC, Cynerd commented on src/rpctypes.md
> +Any value that allow *Null* (such as `i|n`) can be left out if all further items
```suggestion
Any value that allows *Null* (such as `i|n`) can be left out if all further items
```

2025-01-02 19:36 UTC, syyyr commented on src/rpctypes.md
> +integer          = "i", ["(", [number], ",", [number], ")"], unit;
>Unit is actually an optional text and thus it can be no text and thus still present.
Why is it not defined the other way around? As in, `unit = text`, and then make unit optional inside integer. I guess it doesn't matter, but it seems more intuitive to me.

2025-01-02 19:36 UTC, syyyr commented on src/rpctypes.md
> +text             = char, {char};
nit:
```suggestion
text             = character, {character};
```
Or rename character to char

2025-01-02 19:43 UTC, Cynerd commented on src/rpctypes.md
> +integer          = "i", ["(", [number], ",", [number], ")"], unit;
I was trying to improve readibility be reducing complexity. There was just load of brackets in the type definitions and thus I made it optional this way instread. I can move it back but then unit is just the same as text and unit is used only to tell reader what it is suppose to be.

2025-01-06 10:51 UTC, fvacek requested changes

2025-01-06 10:51 UTC, fvacek commented on src/rpcmethods/broker.md
> +| `clientInfo` | `.broker` |       | `i`        | `{?}\|n`    | SuperService |
fix `subscriptions`  in example, pls

2025-01-06 10:51 UTC, fvacek commented on src/rpcmethods/broker.md
> +| `mountedClientInfo` | `.broker` |       | `s`        | `{?}\|n`    | SuperService |
fix subscriptions in example, pls

2025-01-06 10:51 UTC, fvacek commented on src/rpcmethods/broker.md
> +| `clientInfo` | `.broker` |       | `i`        | `{?}\|n`    | SuperService |
```suggestion
| `clientInfo` | `.broker` |       | `i`        | `{i:clientId,s|n:userName,s|n:mountPoint,{i\|n}:subscriptions}|n\|n`    | SuperService |
```
what about to define mandatory fields, it is much more descriptive than `{?}`

2025-01-06 10:51 UTC, fvacek commented on src/rpcmethods/broker.md
> +| `info` | `.broker/currentClient` | Getter |            | `{?}\|n`    | Browse |
fix subscriptions in example, pls

2025-01-06 11:06 UTC, Cynerd commented on src/rpcmethods/broker.md
> +| `clientInfo` | `.broker` |       | `i`        | `{?}\|n`    | SuperService |
Actually the suggestion lies about what is possible as it lefts out possibility that there can be other fields. The typing supports either Structure or Map and I think that allowing mixed definition (structure that can also serve as map) might be door to the bad design.

2025-01-12 16:48 UTC, fvacek requested changes

2025-01-12 16:48 UTC, fvacek commented on src/rpcmethods/broker.md
> +| `clientInfo` | `.broker` |       | `i`        | `!clientInfo\|n` | SuperService |
Since `clientInfo` id type, then I suggest to use `!ClientInfo`. This is better aligned with C++ and Rust code style.

2025-01-13 08:18 UTC, Cynerd commented on src/rpcmethods/broker.md
> +| `clientInfo` | `.broker` |       | `i`        | `!clientInfo\|n` | SuperService |
I think that the C++ or Rust convention is unrelated here. Rather, this is consistent with the naming convention used in this standard (look at the rest of the standard that is based on the API previously introduced by you, like login). But I think that it really doesn't matter what is used in the standard. Consider https://gitlab.com/silicon-heaven/shvc/-/blob/master/include/shv/rpcdir.h?ref_type=heads#L52, where the name is rewritten within the native language style.

2025-01-14 14:43 UTC, Cynerd commented
I created an initial implementation for working with RPC types in pySHV here: https://gitlab.com/silicon-heaven/pyshv/-/merge_requests/6.

2025-01-21 18:04 UTC, merged